### ISSUE TITLE
Modal functionality

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#76] opened 2023-08-29 12:37 UTC
Opening a modal on the PDP happens via a button: https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=1743-13021&mode=design&t=DInHotzAKaDpuUqU-4

### Requirements
- ~Add button variant with plus icon~
- The modal is fullscreen: as wide as the viewport and as tall as the viewport
- The close button of the modal is sticky on scroll
- Content editors can add content to the modal.

**NOTE**: This is a PoC, testing not included until we implement the modal content

**Comment by ZoeBeykirch** [comment] 2023-09-06 12:18
Yes this needs to be done for the PDP page, but this go-live date will not be until January

**Comment by shirin27** [comment] 2023-09-06 12:36
@ZoeBeykirch then I suggest we remove the MVP label, as we use this to determine the issues we need to complete by October. I will add this to a follow-up sprint, after October.

**Comment by Gonzalo-CG** [comment] 2023-10-03 12:22
**Description** 
A button with the following structure "+ [text]" can be present on the [v2 Section Header blocks](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/150). Upon clicking, a modal following the design shown in [Figma- Modal Top Bar](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=1743-13020&mode=design&t=YCYQQHbD5QifZd5L-0) opens.

The scope of this ticket is to handle only the button opening an empty modal, modal content will be added later.

**Acceptance Criteria** 

- [ ] On-click, the button opens the empty modal shown in the Figma files.

**Comment by Andrei-Boiangiu** [comment] 2023-11-23 14:53
confirmed as done
  as tested on https://76-modal--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/modal

**Comment by Andrei-Boiangiu** [comment] 2023-11-28 07:53
reopened and moved back to testing to retest the additional Acceptance Criteria "Content editors can add content to the modal"

**Comment by DanielaPedrochevd** [comment] 2023-11-28 09:14
This ticket took extra effort because we solved ticket #252 with this ticket too. lowering the scope for sprint 8.

**Comment by Andrei-Boiangiu** [comment] 2023-11-28 11:55
additional Critaria and feature has been retested. content editors should now be able to add content to the modal
 closing as Done

**Closed by Andrei-Boiangiu** 2023-11-28 11:55 UTC
Labels: PDP, Spillover
